 import { StateGraph, START, END } from "@langchain/langgraph";
import { ChatOpenAI } from "@langchain/openai";
import { ChatGoogleGenAI } from "@langchain/google-genai";
import { ChatAnthropic } from "@langchain/anthropic";
import { z } from "zod";
import { GraphStateAnnotation, GraphState, ReviewComment } from "./types.js";

// 全局一键切换开关
const CURRENT_PROVIDER = "gemini"; 
const CURRENT_MODEL = "gemini-1.5-pro";    

function getModelInstance(temperature: number) {
  const config = {
    temperature: temperature,
  };

  switch (CURRENT_PROVIDER) {
    case "openai":
      return new ChatOpenAI({
        ...config,
        modelName: CURRENT_MODEL,
        openAIApiKey: process.env.OPENAI_API_KEY,
      });
    case "deepseek":
      return new ChatOpenAI({
        ...config,
        modelName: CURRENT_MODEL,
        openAIApiKey: process.env.DEEPSEEK_API_KEY,
        configuration: { baseURL: "https://api.deepseek.com/v1" },
      });
    case "gemini":
      return new ChatGoogleGenAI({
        ...config,
        modelName: CURRENT_MODEL,
        apiKey: process.env.GEMINI_API_KEY,
      });
    case "claude":
      return new ChatAnthropic({
        ...config,
        modelName: CURRENT_MODEL,
        apiKey: process.env.ANTHROPIC_API_KEY,
      });
    default:
      throw new Error(`Unsupported provider: ${CURRENT_PROVIDER}`);
  }
}
  
const CommentSchema = z.object({
  path: z.string().describe("Relative file path being audited (e.g., 'src/utils.ts')."),
  line: z.number().describe("Precise relative line number on the right side of the diff."),
  body: z.string().describe("The actual detailed review content formatted in markdown. Include standard-compliant code fixes."),
});

const MultiAgentReviewResultSchema = z.object({
  comments: z.array(CommentSchema).describe("Set of code quality comments generated by the auditor."),
});

type OutputSchemaType = z.infer<typeof MultiAgentReviewResultSchema>;

/**
 * Executes a specialized domain review on raw code diffs using GPT-4o.
 */
async function executeAuditor(
  prompt: string,
  diff: string,
  temperature: number
): Promise<ReviewComment> {
const apiKey = CURRENT_PROVIDER === "deepseek" ? process.env.DEEPSEEK_API_KEY : process.env.OPENAI_API_KEY;
const baseURL = CURRENT_PROVIDER === "deepseek" ? "https://api.deepseek.com/v1" : undefined;

const model = new ChatOpenAI({
  modelName: CURRENT_MODEL,
  temperature: temperature,
  openAIApiKey: apiKey,
  configuration: baseURL ? { baseURL } : undefined
}).withStructuredOutput(MultiAgentReviewResultSchema);


  try {
    const rawResponse = await model.invoke();
    const response = rawResponse as OutputSchemaType;
    return response.comments;
  } catch (error) {
    console.error(`Auditor execution error occurred: ${(error as Error).message}`);
    return;
  }
}

/**
 * Node: style_auditor
 * Reviews style guidelines, ESLint, naming paradigms and structural code format.[span_64](start_span)[span_64](end_span)
 */
async function styleAuditorNode(state: GraphState): Promise<Partial<GraphState>> {
  const systemPrompt = `You are a Senior Technical Linter and Code Style Auditor. Your mandate is to analyze code changes for formatting issues, naming convention deviations, ESLint warnings, and improper file architectures.
Strictly ensure that your suggestions map to the exact added line numbers provided in the diff.
If no code style violations are discovered, output an empty comments array.`;

  const comments = await executeAuditor(systemPrompt, state.diff, 0.1);
  return { styleComments: comments };
}

/**
 * Node: security_scanner
 * Audits code base for credential exposure, SQL Injection, and unsafe constructs.[span_65](start_span)[span_65](end_span)
 */
async function securityScannerNode(state: GraphState): Promise<Partial<GraphState>> {
  const systemPrompt = `You are an elite Static Application Security Testing (SAST) Scanner. Your mandate is to inspect code changes for hardcoded api secrets, database passwords, cross-site scripting (XSS), SQL injection, raw shell execution, and cryptographic vulnerabilities.
Focus only on true positives and high-impact security threats.
Strictly ensure that your suggestions map to the exact added line numbers provided in the diff.`;

  const comments = await executeAuditor(systemPrompt, state.diff, 0.0);
  return { securityComments: comments };
}

/**
 * Node: logic_reviewer
 * Investigates potential algorithmic bugs, complexity bounds, and edge crashes.[span_66](start_span)[span_66](end_span)
 */
async function logicReviewerNode(state: GraphState): Promise<Partial<GraphState>> {
  const systemPrompt = `You are a Principal Software Engineer specialized in algorithmic design and distributed systems. Your mandate is to analyze code changes for functional bugs, improper resource allocation, boundary logic flaws, race conditions, memory leaks, and performance scaling issues (e.g., O(N^2) complexity in hot paths).
Suggest concrete fixes and optimizations inside your markdown feedback.
Strictly ensure that your suggestions map to the exact added line numbers provided in the diff.`;

  const comments = await executeAuditor(systemPrompt, state.diff, 0.2);
  return { logicComments: comments };
}

/**
 * Node: aggregator
 * Consolidates all raw review outputs, resolves contradictions, and deduplicates reviews.
 */
async function aggregatorNode(state: GraphState): Promise<Partial<GraphState>> {
  const allComments = [
   ...state.styleComments,
   ...state.securityComments,
   ...state.log[span_12](start_span)[span_12](end_span)[span_14](start_span)[span_14](end_span)icComments,
  ];

  if (allComments.length === 0) {
    return { finalComments: };
  }

  const model = new ChatOpenAI({
    modelName: "gpt-4o",
    temperature: 0.1,
  }).withStructuredOutput(MultiAgentReviewResultSchema);

  const aggregatorSystemPrompt = `You are a Principal Architect and Code Quality Gatekeeper. You have received raw, parallel code review inputs from stylistic, security, and algorithmic logic agents.
Your task is to:
1. Merge duplicate comments addressing the same target lines.
2. Resolve any direct contradictions between different reviews.
3. Formulate a single, cohesive, highly professional review comment for each target code segment.
4. Maintain a supportive, constructive, and engineering-excellent tone.`;

  try {
    const rawResponse = await model.invoke();
    const response = rawResponse as OutputSchemaType;
    return { finalComments: response.comments };
  } catch (error) {
    console.error(`Aggregator node execution failed: ${(error as Error).message}. Returning fallback concatenation.`);
    return { finalComments: allComments };
  }
}

/**
 * Compiles the GraphStateAnnotation topology into an executable parallel execution graph.[span_67](start_span)[span_67](end_span)[span_68](start_span)[span_68](end_span)
 */
export function buildEngineWorkflow() {
  const graph = new StateGraph(GraphStateAnnotation)
   .addNode("style_auditor", styleAuditorNode)
   .addNode("security_scanner", securityScannerNode)
   .addNode("logic_reviewer", logicReviewerNode)
   .addNode("aggregator", aggregatorNode)
    // Establish parallel fan-out
   .addEdge(START, "style_auditor")
   .addEdge(START, "security_scanner")
   .addEdge(START, "logic_reviewer")
    // Establish parallel fan-in to aggregator node
   .addEdge("style_auditor", "aggregator")
   .addEdge("security_scanner", "aggregator")
   .addEdge("logic_reviewer", "aggregator")
   .addEdge("aggregator", END);

  return graph.compile();
}
