name: Publish to NPM
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Clean and Fix Encoding
        run: |
          node -e "const fs = require('fs'); let c = fs.readFileSync('src/bin.js', 'utf8'); c = c.replace(/^\uFEFF/, '').replace(/\r\n/g, '\n'); fs.writeFileSync('src/bin.js', c);"
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
